# Generated by Django 4.1 on 2022-08-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traine_name', models.CharField(max_length=255)),
                ('traine_spec', models.CharField(max_length=255)),
                ('traine_image', models.ImageField(upload_to='trainers')),
            ],
        ),
    ]
