# Generated by Django 4.1 on 2022-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pricing_price_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=255)),
                ('t_email', models.EmailField(max_length=254)),
                ('t_height', models.CharField(max_length=255)),
                ('t_weight', models.CharField(max_length=250)),
                ('booked_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
