# Generated by Django 4.1 on 2022-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='t_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='t_weight',
            field=models.IntegerField(),
        ),
    ]
